### ISSUE TITLE
Clean up logic in socketRecvDataPrefix

### ISSUE THREAD

**Issue by tpecar-ltek** [FreeRTOS/FreeRTOS-Cellular-Interface-Reference-Quectel-BG96#4]
In function

https://github.com/FreeRTOS/FreeRTOS-Cellular-Interface-Reference-Quectel-BG96/blob/c33a3628e015f88df24b21160ba9dbdabc781da1/source/cellular_bg96_api.c#L1690-L1694

Pointer to stack allocated buffer is reused to point to caller provided buffer

---

https://github.com/FreeRTOS/FreeRTOS-Cellular-Interface-Reference-Quectel-BG96/blob/c33a3628e015f88df24b21160ba9dbdabc781da1/source/cellular_bg96_api.c#L1702
https://github.com/FreeRTOS/FreeRTOS-Cellular-Interface-Reference-Quectel-BG96/blob/c33a3628e015f88df24b21160ba9dbdabc781da1/source/cellular_bg96_api.c#L1696
https://github.com/FreeRTOS/FreeRTOS-Cellular-Interface-Reference-Quectel-BG96/blob/c33a3628e015f88df24b21160ba9dbdabc781da1/source/cellular_bg96_api.c#L1718
https://github.com/FreeRTOS/FreeRTOS-Cellular-Interface-Reference-Quectel-BG96/blob/c33a3628e015f88df24b21160ba9dbdabc781da1/source/cellular_bg96_api.c#L1754-L1756
https://github.com/FreeRTOS/FreeRTOS-Cellular-Interface-Reference-Quectel-BG96/blob/c33a3628e015f88df24b21160ba9dbdabc781da1/source/cellular_bg96_api.c#L1770

---

While the logic covers all cases and thus manages to avoid passing the stack buffer back to caller, it's non-trivial and might be error prone, particularly if this port is used as a reference for other devices.

**Comment by tpecar-ltek** [comment]
On a related note, in `_Cellular_RecvFuncData` callback, the `dataLen` is abused to refer to target buffer length (`Cellular_SocketRecv()`'s `bufferLength`), instead of the length of `pData`

https://github.com/FreeRTOS/FreeRTOS-Cellular-Interface-Reference-Quectel-BG96/blob/c33a3628e015f88df24b21160ba9dbdabc781da1/source/cellular_bg96_api.c#L1277-L1280

https://github.com/FreeRTOS/FreeRTOS-Cellular-Interface-Reference-Quectel-BG96/blob/c33a3628e015f88df24b21160ba9dbdabc781da1/source/cellular_bg96_api.c#L2526-L2534

Constructs like these make this particular implementation hard to understand.

**Comment by chinglee-iot** [comment]
This PR is addressed in #13 with more comments and clean up the logic in this function. Thank you for your feedback.
