### ISSUE TITLE
Consider using prefix context to avoid re-parsing in data receive callback

### ISSUE THREAD

**Issue by tpecar-ltek** [FreeRTOS/FreeRTOS-Cellular-Interface-Reference-Quectel-BG96#5]
See https://github.com/FreeRTOS/FreeRTOS-Cellular-Interface/issues/127#issuecomment-1378338587

**Comment by chinglee-iot** [comment]
Most of the time the comm interface returns data in batch and the line only needs to be parsed once. Currently, we don't have plan for this enhancement. 

I will close this issue first. Feel free to re-open this issue for further update or create a PR to improve.
Thank you for the suggestion.
